### ISSUE TITLE
GetVideoUrl/biliDownLoad.py HTTP Error: 400 

### ISSUE THREAD

**Issue by qyvlik** [Vespa314/bilibili-api#11]
貌似 b 站姥爷知道了，修改了接口。

如下为报错提示。

```
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>D:\用户目录\Desktop\bilibiliUrlDownLoad.py http://www.bil
ibili.com/video/av4061686/
['appkey', 'id', 'page', 'type']
appkey=85eb6835b0a1034e&id=4061686&page=1&type=json&sign=64abb11c3ae20734d8d5f6e
c75ae85be
['appkey', 'cid', 'otype', 'quality', 'type']
appkey=85eb6835b0a1034e&cid=None&otype=json&quality=4&type=mp4&sign=ac49b3ee2239
625143ae70924121a357
Traceback (most recent call last):
  File "D:\用户目录\Desktop\bilibiliUrlDownLoad.py", line 76, in <module>
    media_urls = GetBilibiliUrl(sys.argv[1])
  File "D:\用户目录\Desktop\bilibiliUrlDownLoad.py", line 41, in GetBilibiliUrl
    resp_media = urlfetch(url_get_media+sign_1)
  File "D:\用户目录\Desktop\bilibiliUrlDownLoad.py", line 70, in urlfetch
    return urllib2.urlopen(req).read()
  File "D:\Program Files\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Program Files\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "D:\Program Files\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Program Files\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "D:\Program Files\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "D:\Program Files\Python27\lib\urllib2.py", line 558, in http_error_defau
lt
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

C:\Users\Administrator>
```

**Comment by cnbeining** [comment]
自己的KEY一夜之间全死了。

**Comment by qyvlik** [comment]
在某位司机的修复https://github.com/cnbeining/Biligrab/commit/55ecddd896a60abc1881e3dfa706b056122f26ba
